[package]
name = "garfield_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
enum-iterator = "2.1.0"
poise = "0.6.1"
rand = "0.9.0"
reqwest = "0.12.12"
scraper = "0.23.1"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
